### ISSUE TITLE
Add URL to HTTP Basic Auth Pop Up Window

### ISSUE THREAD

**Issue by Francewhoa** [M-Gregoire/Firefox-AddUrlToWindowsTitle#1]
This is a suggestion for a new feature

URL in title (url-in-title-keepass) is presently not able to add the URL to [HTTP Basic Auth pop up](https://en.wikipedia.org/wiki/Basic_access_authentication). With large amount of HTTP Basic Auth pop ups it's hard and slow to scroll through a long list to find the correct entry.

Steps to reproduce

1. Go to https://www.httpwatch.com/httpgallery/authentication/#showExample10
2. Click on "DISPLAY IMAGE" button
3. The HTTP Basic Auth pop up window will open. Notice that the URL was not added to the HTTP Basic Auth pop up title. This is the challenge. 
![http-basic-auth](https://user-images.githubusercontent.com/119942/40858861-93b38194-6594-11e8-9913-cc49ec3d8936.jpg)
4. The suggested new feature expected result is a URL would be added to the HTTP Basic Auth pop up title.
`Authentication Required - https://<URL.HERE>`
Instead of `Authentication Required`

[keepass-helper](https://addons.mozilla.org/en-US/firefox/addon/keepass-helper/) add-on is able to do add URL to HTTP Basic Auth pop up. **Maybe some of its [open source code](https://app.assembla.com/wiki/show/slipstream/KeePass_Helper ) could be recycled for url-in-title-keepass?**

Any volunteer for a patch? I would be happy to contribute testing and or documentation.

Using:

- url-in-title-keepass 1.0
- Firefox 52.8 at 64 bit
- Debian 8 Jessie

**Comment by Francewhoa** [comment]
**Workaround**
This is a temporary workaround. This [MultiPass Disarmed for HTTP basic auth](https://addons.mozilla.org/en-US/firefox/addon/multipass-disarmed/) add-on is able to store HTTP Basic Authentication credentials. 

**Strength**
- Allow you to automatically enter the HTTP Basic Auth credentials. Then use _Firefox-AddUrlToWindowsTitle_ add-on and KeePass(X/XC) or equivalent for the remaining form(s).
- [Open source](https://github.com/excitoon/MultiPassDisarmed)
- No spyware

**Challenge**
It seems to presently have weak storage security. In plain text. I mean a not authorized person with access to your computer would be able to read anything stored using this add on. Such as HTTP Basic Authentication URLs, usernames, and passwords. Related ticket at https://github.com/excitoon/MultiPassDisarmed/issues/2

**Suggestion**
 Use this add-on only for appropriate sites. Which do not contain sensitive information. Or off-line.

**Comment by M-Gregoire** [comment]
Thank you for your suggestion. However, according to my question on [StackOverflow](https://stackoverflow.com/questions/50772853/edit-basic-authorization-window), the WebExtension API does not allow to change the title of the Basic Auth window.

I believe [Keepass helper](https://addons.mozilla.org/en-US/firefox/addon/keepass-helper/) was able to do it because it used the old extension format (which is why it's incompatible with Firefox Quantum). I will check the source code just to be sure.

I would suggest using [Kee (used to be Keefox)](https://addons.mozilla.org/fr/firefox/addon/keefox/) with the client plugin which is able to automatically fill Basic Auth using your Keepass database. All the communication is encrypted.

**Comment by M-Gregoire** [comment]
[This](https://stackoverflow.com/questions/45666306/change-basic-http-authentication-realm-and-login-dialog-message) topic seems to confirm "that the login prompt/dialog is a response built into the user-agent/browser and cannot be changed by the server".
Thank you for your suggestion though.
